version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: aamira-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: aamira-courier

volumes:
  mongodb_dev_data:
